version: "3.8"
services:
    rabbitmq-dev:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - microservices
    consul-dev:
        image: consul:1.15.2
        container_name: consul
        ports:
            - '8500:8500'
            - '8600:8600/udp'
        command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'
        networks:
            - microservices
      
    # connection-builder-service:
    #     build: ./connection-builder
    #     environment:
    #         - SPRING_CLOUD_CONSUL_HOST=consul
    #     depends_on:
    #         - rabbitmq-dev
    #         - consul-dev
    #     restart: on-failure
    #     ports:
    #         - 8081:8081
    #     networks:
    #         - microservices
            
    # master-data-service:
    #     build: ./master-data
    #     environment:
    #         - SPRING_CLOUD_CONSUL_HOST=consul
    #     depends_on:
    #         - rabbitmq-dev
    #         - consul-dev
    #     restart: on-failure
    #     ports:
    #         - 8082:8082
    #     networks:
    #         - microservices
            
    # gateway:
    #     build: ./gateway
    #     environment:
    #         - SPRING_CLOUD_CONSUL_HOST=consul
    #     depends_on:
    #         - rabbitmq-dev
    #         - consul-dev
    #     ports:
    #         - 8000:8000
    #     networks:
    #         - microservices
            
    # frontend:
    #     build: frontend-react-service
    #     ports:
    #         - 3000:80
            
networks:
  microservices:
    driver: bridge
